### ISSUE TITLE
TmxProperties.saveTimexPropertyFile() causes NullPointerException

### ISSUE THREAD

**Issue by pnerg** [pnerg/timex#1]
Stacktrace

```
SEVERE: Could not save properties
java.lang.NullPointerException
    at org.dmonix.xml.XMLUtil.normalizeDocument(XMLUtil.java:457)
    at org.dmonix.xml.XMLUtil.normalizeDocument(XMLUtil.java:469)
    at org.dmonix.xml.XMLUtil.normalizeDocument(XMLUtil.java:469)
    at org.dmonix.xml.XMLUtil.saveToFile(XMLUtil.java:985)
    at org.dmonix.xml.XMLPropertyHandler.savePropertyFile(XMLPropertyHandler.java:98)
    at org.dmonix.timex.properties.TmxProperties.saveTimexPropertyFile(TmxProperties.java:46)
    at org.dmonix.timex.gui.TmxFrame.exitTimex(TmxFrame.java:358)
    at org.dmonix.timex.gui.TmxFrame.access$1800(TmxFrame.java:56)
    at org.dmonix.timex.gui.TmxFrame$TmxFrame_this_windowAdapter.windowClosing(TmxFrame.java:704)
    at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
    at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
    at java.awt.Window.processWindowEvent(Window.java:2051)
    at javax.swing.JFrame.processWindowEvent(JFrame.java:296)
    at java.awt.Window.processEvent(Window.java:2009)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.awt.EventQueue$4.run(EventQueue.java:718)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by pnerg** [comment]
Short term solution is to ignore saving the settings/properties...think we can live with that
